networks:
  axi-network:
    driver: bridge

services:
  axigen:
    image: axigen/axigen
    ports:
      - "80:80"
      - "443:443"
      - "993:993"
      - "995:995"
      - "25:25"
      - "465:465"
      - "7000:7000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - ".:/axigen/var"
    networks:
      - axi-network